1.30 nvidia driver update, af fix

diff --git a/nvidia-tool b/nvidia-tool
--- a/nvidia-tool
+++ b/nvidia-tool
@@ -113,6 +113,73 @@ function flash_bios () {
 	"
 }
 
+function driver_install () {
+	url=$1
+	
+	df=`df | grep "/$" | awk '{print $4}'`; echo $df
+	[[ $df -lt 500000 ]] && echo -e "${RED}You don\`t have enough disk space. Try to delete something or disk-expand. Exiting...${WHITE}" && exit 1
+		
+	if [[ -z $url ]]; then
+		echo -e "${CYAN}> Getting the latest version${WHITE}"
+		versions_url="https://os.dog/downloads/drivers/driver_versions.txt"
+		versions=`curl -sLk $versions_url`
+		[[ -z $versions ]] && echo -e "${RED}Error downloading versions from $versions_url${WHITE}" && return 1
+		eval "$versions"
+		url="https://os.dog/downloads/drivers/${LATEST_NVIDIA}"
+	fi
+
+	current_driver=`nvidia-smi | grep "Driver Version" | sed 's/.*Driver Version: \([0-9.]*\)\s.*/\1/'`
+	echo -e "Current driver:\t${GREEN}$current_driver${WHITE}"
+	echo -e "New driver:\t${GREEN}${LATEST_NVIDIA}${WHITE}"
+	echo -e "Are you really want to update driver? y/n"
+	read answer
+	if [[ $answer != 'y' &&  $answer != 'yes' && $answer != 'Y' && $answer && 'Yes' ]]; then
+		echo -e "${RED}OK, bye!${WHITE}"
+		exit 1
+	fi
+	services_stop
+
+	cd "/dog/downloads"
+	driver_name=`basename $url`
+
+	if [[ -e ./$driver_name ]]; then
+		echo -e "${CYAN}> Driver $driver_name is already downloaded${WHITE}"
+	else
+		echo -e "${CYAN}> Downloading $url${WHITE}"
+		rm -f "/tmp/$driver_name"
+		wget -c $url -O "/tmp/$driver_name" #`[ -t 0 ] && echo '--no-verbose'`
+		mv "/tmp/$driver_name" "/dog/downloads/$driver_name"
+		[[ $? -ne 0 ]] && echo -e "${RED}Error downloading driver${WHITE}" && exit 1
+	fi
+
+
+	echo -e "${CYAN}> Installing${WHITE}"
+	#apt update
+	#apt-get install -y dkms
+	sh "$driver_name" --accept-license --no-questions --ui=none --install-libglvnd #--dkms 
+	exitcode=$?
+	hello
+
+	if [[ $exitcode -eq 0 ]]; then
+			echo -e ""
+			echo -e "${CYAN}> Updating nvidia-settings${WHITE}"
+			apt update
+			nvidia_settings_version=`dpkg -s nvidia-settings 2>&1 | grep '^Version: ' | sed 's/Version: //'`
+			if [[ -z "$nvidia_settings_version" ]]; then
+				echo -e "nvidia-setting is not installed, installing"
+				apt-get install --reinstall -y nvidia-settings
+			else
+				echo -e "nvidia-setting is installed, upgrading"
+				apt-get install --only-upgrade --reinstall -y nvidia-settings
+			fi
+			services_start
+			echo -e "${GREEN}Installation complete, reboot please${WHITE}"
+	else
+		services_start
+		echo -e "${RED}Error installing driver${WHITE}" && exit 1
+	fi
+}
+
 case $1 in
 	services_start|start)
 		services_start
@@ -129,12 +196,17 @@ case $1 in
 	flash_bios|flash)
 		flash_bios $2 $3 "$4"
 	;;
+	driver_install|update)
+		driver_install $2
+	;;
 	*)
 		bname=`basename $0`
-		echo -e "Usage: ${CYAN}$bname start|stop|save gpu_id file|get_bios gpu_id${WHITE}"
+		echo -e "Usage: ${CYAN}$bname start|stop|install|save gpu_id file|get_bios gpu_id${WHITE}"
 		echo -e "  start, services_start\t\tStart mining, X-server, load Nvidia modules"
 		echo -e "  stop, services_stop\t\tStop mining, X-server, load Nvidia modules"
 		echo -e "  get_bios, bios_ver gpu_id\tGet bios version "
 		echo -e "  save, save_bios gpu_id file\tSave Nvidia GPU bios"
+		echo -e "  update, driver_install\tUpdate Nvidia driver to latest or argument version"
+		echo -e "  \t\t\t\te .g. driver-update nvidia http://ru.download.nvidia.com/XFree86/Linux-x86_64/418.56/NVIDIA-Linux-x86_64-418.56.run"
 	;;
 esac
