1.49 nvidia-oc for 1660, upp install

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -62,7 +62,16 @@ eval "$versions"
 upgrade_deb dog-libs $dog_libs
 upgrade_deb dog-sbin $dog_sbin
 
-apt-get -q=2 install lm-sensors expect hddtemp libnetfilter-queue1 libssl1.0
+apt-get -q=2 install lm-sensors expect hddtemp libnetfilter-queue1 libssl1.0 python3-setuptools
+upp > /dev/null 2>&1
+exitcode=$?
+if [[ $exitcode -ne 0 ]]; then
+	echo -e "${GREEN}> Uplift Power Play installing${WHITE}"
+	cd /dog/sbin/upp/
+	python3 ./setup.py install > /dev/null 2>&1
+	exitcode=$?
+	[[ $exitcode -eq 0 ]] && echo -e "${GREEN}> Uplift Power Play installed${WHITE}" || echo -e "${RED}> Error while installing Uplift Power Play${WHITE}"
+fi
 
 crontab="/var/spool/cron/crontabs/root"
 crontab_remove="/dog/service/crontab.root.remove"
